utils::globalVariables(c(
  ".", ":=",
  "n", "true_effect", "ok", "pass", "assurance",
  "post_prob_direction", "post_prob_threshold", "post_prob_rope",
  "power_direction", "power_threshold", "power_rope",
  "avg_ci_width", "ci_coverage",
  "ciw_q05", "ciw_q25", "ciw_q50", "ciw_q75", "ciw_q95",
  "avg_post_prob_direction", "avg_post_prob_threshold", "avg_post_prob_rope",
  "bf10", "bf_hit_3", "bf_hit_10", "log10_bf10", "mean_log10_bf", "nsims_ok",
  "scenario", "ymin", "ymax", "ymid", "p_star",
  "q05", "q25", "q50", "q75", "q95", "ci_width",
  "mean_", "sd_","hit", "hits", "trials", "lo", "hi", "sim", "conditional_power",
  "._ok_all","n_recommended","value",
  "sample_size", ".w", "sims_used", "effect_val",
  "had_warning", "warning_msg", "log_mlik", "mode_ok",
  "prop_warned", "n_failed", "mlik_min", "mlik_max", "mlik_median", "n_mode_ok",
  "sampled_error_sd", "sampled_group_sd",
  "mean_sampled_error_sd", "sd_sampled_error_sd",
  "mean_sampled_group_sd", "sd_sampled_group_sd",
  "prior", "eff_label", "density", "x"
))